"use client";

import { useState } from "react";
import { useAuth } from "@clerk/nextjs";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Copy, Key, RefreshCw, Eye, EyeOff } from "lucide-react";
import { toast } from "sonner";

export function ApiKeys() {
  const { getToken } = useAuth();
  const [showKey, setShowKey] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  // For now, we'll show the Clerk session token as the API key
  // In production, this would be a separate API key generated by the backend
  const [apiKey, setApiKey] = useState<string>("");

  const fetchApiKey = async () => {
    setIsLoading(true);
    try {
      const token = await getToken();
      if (token) {
        setApiKey(token);
      }
    } catch (error) {
      toast.error("Failed to get API key");
    } finally {
      setIsLoading(false);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(apiKey);
    toast.success("API key copied to clipboard");
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>API Keys</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <Skeleton className="h-12 w-full" />
          <Skeleton className="h-10 w-32" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>API Keys</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-muted-foreground mb-4">
          Use your Clerk session token to authenticate with the Mnemosyne API.
        </p>

        {!apiKey ? (
          <Button onClick={fetchApiKey}>
            <Key className="h-4 w-4 mr-2" />
            Reveal API Key
          </Button>
        ) : (
          <div className="space-y-4">
            <div className="flex gap-2">
              <div className="relative flex-1">
                <Input
                  type={showKey ? "text" : "password"}
                  value={apiKey}
                  readOnly
                  className="pr-20 font-mono text-sm"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  className="absolute right-8 top-1/2 -translate-y-1/2 h-6 w-6 p-0"
                  onClick={() => setShowKey(!showKey)}
                >
                  {showKey ? (
                    <EyeOff className="h-3 w-3" />
                  ) : (
                    <Eye className="h-3 w-3" />
                  )}
                </Button>
              </div>
              <Button variant="outline" size="icon" onClick={copyToClipboard}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>

            <div className="flex gap-2">
              <Badge variant="secondary">Active</Badge>
              <span className="text-xs text-muted-foreground">
                Use this token in the Authorization header: Bearer {'<token>'}
              </span>
            </div>

            <Button variant="outline" size="sm" onClick={fetchApiKey}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh Token
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
